lib/tergeo_web/router.ex
defmodule TergeoWeb.Router do
  use TergeoWeb.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers

    plug TergeoWeb.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TergeoWeb do
    pipe_through :browser

    get "/", GroupController, :index
  end

  scope "/", TergeoWeb do
    pipe_through [:browser, TergeoWeb.Plugs.RequireLogin]

    resources "/chores", ChoreController, only: [:index, :show, :new, :create]
    get "/chores/:id/complete_chore", ChoreController, :complete_chore

    resources "/groups", GroupController
  end

  scope "/auth", TergeoWeb do
    pipe_through :browser

    get "/signout", AuthController, :delete
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :new
  end

end

web/router.ex
defmodule Tergeo.Router do
  use Tergeo.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Tergeo do
    pipe_through :browser 

    get "/", PageController, :index
    
    resources "/chores", ChoreController, only: [:index]
  end
  
end

lib/tergeo_web/views/layout_view.ex
defmodule TergeoWeb.LayoutView do
  use TergeoWeb.Web, :view
end

lib/tergeo_web/templates/layout/_navigation.html.eex
<nav class="black">
  <div class="nav-wrapper">
    <a href="/" class="brand-logo">Tergeo</a>
    <a href="#" data-target="mobile-demo" class="sidenav-trigger">
      <i class="material-icons">menu</i>
    </a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <%= if @conn.assigns[:user] do %>
        <li class="nav__welcome-message">Welcome <%= @conn.assigns.user.first_name %>!</li>
        <li><%= link "My groups", to: group_path(@conn, :index) %></li>
        <li><%= link "Chores", to: chore_path(@conn, :index) %></li>
        <li><%= link "Add chore", to: chore_path(@conn, :new) %></li>
        <li><%= link "Start a group", to: group_path(@conn, :new), class: "start-group__link" %></li>
        <li><%= link "Sign out", to: auth_path(@conn, :delete) %></li>
      <% else %>
        <li>
          <%= link "Sign in with Google", 
              to: auth_path(@conn, :request, "google", 
              scope: "email profile"), 
              class: "button google-sign-in__link" %>
        </li>
      <% end %>
    </ul>

    <ul id="mobile-demo" class="sidenav">
      <%= if @conn.assigns[:user] do %>
        <li class="nav__welcome-message">Welcome <%= @conn.assigns.user.first_name %>!</li>
        <li><%= link "My groups", to: group_path(@conn, :index) %></li>
        <li><%= link "Chores", to: chore_path(@conn, :index) %></li>
        <li><%= link "Add chore", to: chore_path(@conn, :new) %></li>
        <li><%= link "Start a group", to: group_path(@conn, :new) %></li>
        <li><%= link "Sign out", to: auth_path(@conn, :delete) %></li>
      <% else %>
        <li>
          <%= link "Sign in with Google", 
              to: auth_path(@conn, :request, "google", 
              scope: "email profile"), 
              class: "button google-sign-in__link" %>
        </li>
      <% end %>
    </ul>

  </div>
</nav>

lib/tergeo_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Tergeo!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
    <link rel="stylesheet" href="http://fonts.googleapis.com/icon?family=Material+Icons">
  </head>

  <body>
    <%= render "_navigation.html", conn: @conn %>
    
    <div class="container">


      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
    <script>
      $(document).ready(function() {
        $('select').formSelect();
      });
    </script>
    <script>
      $(document).ready(function(){
        $('.sidenav').sidenav();
      });
    </script>
  </body>
</html>